trigger: none

parameters:
  - name: TRIGGER_TEST
    displayName: Executar pipeline de teste após essa
    type: boolean
    default: true
  - name: OVERRIDE_FILE
    displayName: "Execução manual - File to Run (opcional)"
    type: string
    default: ' '

schedules:

  - cron: '0 3 * * *'
    displayName: 'All - Midnight Build'
    branches:
      include:
        - master
    always: true
  - cron: '0 4 * * *'  # Executa carga
    displayName: 'Load Examples'
    branches:
      include:
        - master
    always: true

variables:
  - name: FILE_INDEX  # define os arquivos que serão executados pela pipeline
    value: "/k6/dist/index.js"

  - name: FILE_EXAMPLE
    value: "/k6/dist/api/project/example/conjunto_example/example_test/example_test.js"

  - name: FILE_ANOTHER_EXAMPLE
    value: "/k6/dist/api/project/example/another_example/another_example_test/another_example_test.js"
    
jobs:
  - job: PublishArtifacts
    displayName: "Publish Artifacts" 
    steps:
      - checkout: none
        displayName: "Git - Checkout"

      - script: |
          echo "Build.Reason = $(Build.Reason)"
          echo "Build.DefinitionName = $(Build.DefinitionName)"

          mkdir -p $(Pipeline.Workspace)/artifacts # testes que serão executados

          K6_FILE_LIST="$(Pipeline.Workspace)/artifacts/k6-files.txt" # cria o arquivo para guardar os testes para execução, já dentro do workspace

          echo ""
          echo "artifacts:"
          "$K6_FILE_LIST"

          if [[ "$(Build.Reason)" == "Schedule" ]]; then  # Execução via CRON

            if [[ "$(Build.CronSchedule.DisplayName)" == "All - Midnight Build" ]]; then   # Todos os teste
              echo "$(FILE_INDEX)" >> "$K6_FILE_LIST"

            elif [[ "$(Build.CronSchedule.DisplayName)" == "Load Examples" ]]; then   # Todas as cargas
              echo "$(FILE_EXAMPLE)" >> "$K6_FILE_LIST"
              echo "$(FILE_ANOTHER_EXAMPLE)" >> "$K6_FILE_LIST"
            fi

          elif [[ "$(Build.Reason)" == "Manual" ]]; then
            
            OVERRIDE_FILE="${{ parameters.OVERRIDE_FILE }}"

            if [[ -n "${OVERRIDE_FILE// /}" ]]; then 
              echo "$OVERRIDE_FILE" >> "$K6_FILE_LIST"
            else
              echo "$(FILE_EXAMPLE)" >> "$K6_FILE_LIST"
              echo "$(FILE_ANOTHER_EXAMPLE)" >> "$K6_FILE_LIST"
            fi

          fi
        displayName: "Define aquivos de execuçao"

      - task: CmdLine@2
        displayName: "Debug variables"
        inputs:
          script: |
            echo "Conteúdo:"
            cat "$(Pipeline.Workspace)/artifacts/k6-files.txt"

            echo ""
            echo "Arquivos:"
            ls -la $(Pipeline.Workspace)

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/artifacts' # publica os artefatos para serem consumidos pela pipeline de teste
          artifact: 'K6FilesToRun'
          publishLocation: 'pipeline'
  
  - job: TriggerPipelines 
    displayName: "[load-test] TriggerPipelines"
    dependsOn: PublishArtifacts
    steps:
      - checkout: none
        displayName: "Git - Checkout"

      - task: PowerShell@2
        displayName: "PowerShell - AddBuildTag - Trigger Test"
        condition: eq('${{ parameters.TRIGGER_TEST }}', true)
        inputs:
          targetType: 'inline'
          script: |
            echo "##vso[build.addbuildtag]trigger-load-test"