# Esse arquivo tem como função o controle de que testes devem ser executados em determinado horário.
# Dependendo do horário, é considerado um conjunto de testes.
# O workflow identifica qual cron disparou a execução

name: app-delivery-test

on:

  schedule:
    - cron: '50 9 * * *'  # um cron
    - cron: '0 4 * * *'   # load cron

  workflow_dispatch: # permite executar manualmente


# Lock (equivalente ao lockBehavior: sequential)
concurrency:
  group: k6-tests
  cancel-in-progress: false


jobs:

  Test:
    name: "[app-delivery-test] Testes"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - cron: '20 10 * * *'  # 10 = 7
            test_file: './index.js' 
            
          - cron: '25 10 * * *'
            test_file: './api/project/example/conjunto_example/example_test/example_test.js'

    steps:

      - name: Git - Checkout
        uses: actions/checkout@v4

      - name: Debug - Print Variables
        run: |
          echo "File to run: ${{ matrix.test_file }}"

      # - name: Debug - Print files
      #   run: |
      #     echo "Files:"
      #     ls -R
          
      - name: RUN - k6 test
        env:
          API_BASE_URL: ${{ vars.API_BASE_URL }}
          API_WARMUP_IN_SECONDS: ${{ vars.API_WARMUP_IN_SECONDS }}
          TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
          NOTIFY_ON_SUCCESS: ${{ vars.NOTIFY_ON_SUCCESS }}
          SEND_NOTIFICATION: ${{ vars.SEND_NOTIFICATION }}
          SEND_NOTIFICATION_TO: ${{ vars.SEND_NOTIFICATION_TO }}
          K6_OUT: experimental-prometheus-rw
          K6_PROMETHEUS_RW_SERVER_URL: ${{ vars.K6_PROMETHEUS_URL }}
          K6_PROMETHEUS_RW_USERNAME: ${{ secrets.K6_PROMETHEUS_USER }}
          K6_PROMETHEUS_RW_PASSWORD: ${{ secrets.K6_PROMETHEUS_PASSWORD }}
        run: |

          mkdir -p ./k6/api/reports
          chmod -R 777 ./k6/api/reports

          docker run --rm \
          -e API_BASE_URL \
          -e API_WARMUP_IN_SECONDS \
          -e TELEGRAM_BOT_ID \
          -e TELEGRAM_CHAT_ID \
          -e NOTIFY_ON_SUCCESS \
          -e SEND_NOTIFICATION \
          -e SEND_NOTIFICATION_TO \
          -e K6_OUT \
          -e K6_PROMETHEUS_RW_SERVER_URL \
          -e K6_PROMETHEUS_RW_USERNAME \
          -e K6_PROMETHEUS_RW_PASSWORD \
          -v ${{ github.workspace }}/k6/utils:/utils \
          -v ${{ github.workspace }}/k6:/k6 \
          -w /k6 \
          -i grafana/k6 run ${{ matrix.test_file }}

# -v $(pwd):/k6 \

      - name: PublishTestResults - k6 - Test Results
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: './k6/api/reports/k6-test_results-junit.xml'
